### ISSUE TITLE
Unable to access sun.* dependency classes

### ISSUE THREAD

**Issue by sgdc3** [Yamakaja/RuntimeTransformer#3]
```
java.lang.NoClassDefFoundError: com/sun/tools/attach/AttachNotSupportedException
        at it.feargames.askyblockfix.ASkyBlockFix.onEnable(ASkyBlockFix.java:37) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[patched_1.12.1.jar:git-Paper-1196]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:316) [patched_1.12.1.jar:git-Paper-1196]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:404) [patched_1.12.1.jar:git-Paper-1196]
        at com.rylinaux.plugman.util.PluginUtil.load(PluginUtil.java:366) [PlugMan.jar:?]
        at com.rylinaux.plugman.util.PluginUtil.load(PluginUtil.java:318) [PlugMan.jar:?]
        at com.rylinaux.plugman.util.PluginUtil.reload(PluginUtil.java:380) [PlugMan.jar:?]
        at com.rylinaux.plugman.command.ReloadCommand.execute(ReloadCommand.java:122) [PlugMan.jar:?]
        at com.rylinaux.plugman.PlugManCommandHandler.onCommand(PlugManCommandHandler.java:95) [PlugMan.jar:?]
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) [patched_1.12.1.jar:git-Paper-1196]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:151) [patched_1.12.1.jar:git-Paper-1196]
        at org.bukkit.craftbukkit.v1_12_R1.CraftServer.dispatchCommand(CraftServer.java:672) [patched_1.12.1.jar:git-Paper-1196]
        at org.bukkit.craftbukkit.v1_12_R1.CraftServer.dispatchServerCommand(CraftServer.java:635) [patched_1.12.1.jar:git-Paper-1196]
        at net.minecraft.server.v1_12_R1.DedicatedServer.aP(DedicatedServer.java:462) [patched_1.12.1.jar:git-Paper-1196]
        at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:425) [patched_1.12.1.jar:git-Paper-1196]
        at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:767) [patched_1.12.1.jar:git-Paper-1196]
        at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:665) [patched_1.12.1.jar:git-Paper-1196]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_141]
Caused by: java.lang.ClassNotFoundException: com.sun.tools.attach.AttachNotSupportedException
        at java.net.URLClassLoader.findClass(URLClassLoader.java:381) ~[?:1.8.0_141]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:102) ~[patched_1.12.1.jar:git-Paper-1196]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:87) ~[patched_1.12.1.jar:git-Paper-1196]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_141]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_141]
        ... 18 more
```
@games647

**Comment by sgdc3** [comment]
I tried both OpenJDK and OracleJDK, version 1.8 release 141
OS: CentOS 6

**Comment by sgdc3** [comment]
I think this happens because i'm using maven, not gradle

**Comment by Yamakaja** [comment]
Could you provide me a bit more information? What's your pom and how did you get the artifact?

**Comment by Yamakaja** [comment]
On the bright side, i managed to reproduce your issue - investigating

**Comment by sgdc3** [comment]
My current pom: https://hastebin.com/sinupuvelu.xml

**Comment by Yamakaja** [comment]
The pom seems fine

**Comment by Yamakaja** [comment]
Apparently #2 didn't quite work as expected ^^

**Comment by sgdc3** [comment]
i tried to use the old version (with included sun.*) and i had another issue about missing agent.jar in the final jar -_- then i manually copied the agent.jar into the final jar and got this:

com.sun.tools.attach.AttachNotSupportedException no providers installed

**Comment by sgdc3** [comment]
I got something more specific: ProviderLinuxAttachProvider not found

**Comment by sgdc3** [comment]
seems like a missing linux implementation :/ idk

**Comment by sgdc3** [comment]
Ok now i managed to install the library to my local repo, now agent.jar is correctly shaded into the final jar but i'm still getting the same excaption:

```
[01:38:44 ERROR]: Error occurred while enabling ASkyBlockFix v1.0-SNAPSHOT (Is it up to date?)
java.lang.NoClassDefFoundError: com/sun/tools/attach/AttachNotSupportedException
        at it.feargames.askyblockfix.ASkyBlockFix.onEnable(ASkyBlockFix.java:36) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[patched_1.12.1.jar:git-Paper-1196]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:316) [patched_1.12.1.jar:git-Paper-1196]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:404) [patched_1.12.1.jar:git-Paper-1196]
        at com.rylinaux.plugman.util.PluginUtil.load(PluginUtil.java:366) [PlugMan.jar:?]
        at com.rylinaux.plugman.util.PluginUtil.load(PluginUtil.java:318) [PlugMan.jar:?]
        at com.rylinaux.plugman.util.PluginUtil.reload(PluginUtil.java:380) [PlugMan.jar:?]
        at com.rylinaux.plugman.command.ReloadCommand.execute(ReloadCommand.java:122) [PlugMan.jar:?]
        at com.rylinaux.plugman.PlugManCommandHandler.onCommand(PlugManCommandHandler.java:95) [PlugMan.jar:?]
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) [patched_1.12.1.jar:git-Paper-1196]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:151) [patched_1.12.1.jar:git-Paper-1196]
        at org.bukkit.craftbukkit.v1_12_R1.CraftServer.dispatchCommand(CraftServer.java:672) [patched_1.12.1.jar:git-Paper-1196]
        at org.bukkit.craftbukkit.v1_12_R1.CraftServer.dispatchServerCommand(CraftServer.java:635) [patched_1.12.1.jar:git-Paper-1196]
        at net.minecraft.server.v1_12_R1.DedicatedServer.aP(DedicatedServer.java:462) [patched_1.12.1.jar:git-Paper-1196]
        at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:425) [patched_1.12.1.jar:git-Paper-1196]
        at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:767) [patched_1.12.1.jar:git-Paper-1196]
        at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:665) [patched_1.12.1.jar:git-Paper-1196]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_141]
Caused by: java.lang.ClassNotFoundException: com.sun.tools.attach.AttachNotSupportedException
        at java.net.URLClassLoader.findClass(URLClassLoader.java:381) ~[?:1.8.0_141]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:102) ~[patched_1.12.1.jar:git-Paper-1196]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:87) ~[patched_1.12.1.jar:git-Paper-1196]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_141]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_141]

```

**Comment by Yamakaja** [comment]
Yeah, this is caused by the fact that the tools.jar classes are not available, contrary to the belief of #2 's issuer. Currently working on an adequate fix

**Comment by sgdc3** [comment]
i tried to add my tools.jar to the classpath, but it doesn't work :/

**Comment by sgdc3** [comment]
java -classpath /opt/jdk1.8.0_141/lib/tools.jar ....... -jar paperclip.jar

**Comment by Yamakaja** [comment]
Does that even launch? I thought you couldn't combine -classpath and -jar 0.o

**Comment by sgdc3** [comment]
yep you can

**Comment by sgdc3** [comment]
but it still throws ClassNotFoundException

**Comment by chrismin13** [comment]
Could you try adding the following classes in your src folder?
http://grepcode.com/file/repository.grepcode.com/java/root/jdk/openjdk/8u40-b25/com/sun/tools/attach/package-info.java
Click on the files tab on the top left, then scroll down and add all the classes under com.sun.tools.attach in your src folder along with all your other code.
That fixed it for me!

**Comment by sgdc3** [comment]
Now i tried adding both tools.jar and the jdk attach source into my jar, just one moment...

**Comment by sgdc3** [comment]
@chrismin13 ok one problem is solved, now it can't find the linux implementation

```
[02:19:17 WARN]: com.sun.tools.attach.AttachNotSupportedException: no providers installed
[02:19:17 WARN]:        at com.sun.tools.attach.VirtualMachine.attach(VirtualMachine.java:203)
[02:19:17 WARN]:        at me.yamakaja.runtimetransformer.RuntimeTransformer.attachAgent(RuntimeTransformer.java:34)
[02:19:17 WARN]:        at me.yamakaja.runtimetransformer.RuntimeTransformer.<init>(RuntimeTransformer.java:28)
[02:19:17 WARN]:        at it.feargames.askyblockfix.ASkyBlockFix.onEnable(ASkyBlockFix.java:36)
[02:19:17 WARN]:        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264)
[02:19:17 WARN]:        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:316)
[02:19:17 WARN]:        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:404)
[02:19:17 WARN]:        at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugin(CraftServer.java:382)
[02:19:17 WARN]:        at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugins(CraftServer.java:331)
[02:19:17 WARN]:        at net.minecraft.server.v1_12_R1.MinecraftServer.t(MinecraftServer.java:442)
[02:19:17 WARN]:        at net.minecraft.server.v1_12_R1.MinecraftServer.l(MinecraftServer.java:403)
[02:19:17 WARN]:        at net.minecraft.server.v1_12_R1.MinecraftServer.a(MinecraftServer.java:341)
[02:19:17 WARN]:        at net.minecraft.server.v1_12_R1.DedicatedServer.init(DedicatedServer.java:290)
[02:19:17 WARN]:        at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:616)
[02:19:17 WARN]:        at java.lang.Thread.run(Thread.java:748)

```

**Comment by sgdc3** [comment]
it seems that the classpath is ignoring the tools.jar file

**Comment by Yamakaja** [comment]
https://github.com/Yamakaja/RuntimeTransformer/commit/3077d85ea0354db0277ad1917d53a94e24dc7d29 should have fixed your issue

**Comment by sgdc3** [comment]
ok, testibg that in 5 mins

**Comment by Yamakaja** [comment]
@sgdc3 Update?

**Comment by sgdc3** [comment]
Just tested, ot works but now i'm getting this:

```
[02:54:36 WARN]: java.lang.RuntimeException: java.lang.ClassNotFoundException: com.wasteofplastic.askyblock.schematics.Schematic
[02:54:36 WARN]:        at org.objectweb.asm.ClassWriter.getCommonSuperClass(Unknown Source)
[02:54:36 WARN]:        at org.objectweb.asm.ClassWriter.a(Unknown Source)
[02:54:36 WARN]:        at org.objectweb.asm.Frame.a(Unknown Source)
[02:54:36 WARN]:        at org.objectweb.asm.Frame.a(Unknown Source)
[02:54:36 WARN]:        at org.objectweb.asm.MethodWriter.visitMaxs(Unknown Source)
[02:54:36 WARN]:        at org.objectweb.asm.tree.MethodNode.accept(Unknown Source)
[02:54:36 WARN]:        at org.objectweb.asm.tree.MethodNode.accept(Unknown Source)
[02:54:36 WARN]:        at org.objectweb.asm.tree.ClassNode.accept(Unknown Source)
[02:54:36 WARN]:        at me.yamakaja.runtimetransformer.transform.ClassTransformer.transform(ClassTransformer.java:52)
[02:54:36 WARN]:        at sun.instrument.TransformerManager.transform(TransformerManager.java:188)
[02:54:36 WARN]:        at sun.instrument.InstrumentationImpl.transform(InstrumentationImpl.java:428)
[02:54:36 WARN]:        at sun.instrument.InstrumentationImpl.retransformClasses0(Native Method)
[02:54:36 WARN]:        at sun.instrument.InstrumentationImpl.retransformClasses(InstrumentationImpl.java:144)
[02:54:36 WARN]:        at me.yamakaja.runtimetransformer.agent.Agent.process(Agent.java:41)
[02:54:36 WARN]:        at me.yamakaja.runtimetransformer.TransformerUtils.attachAgent(TransformerUtils.java:25)
[02:54:36 WARN]:        at me.yamakaja.runtimetransformer.RuntimeTransformer.<init>(RuntimeTransformer.java:29)
[02:54:36 WARN]:        at it.feargames.askyblockfix.ASkyBlockFix.onEnable(ASkyBlockFix.java:36)
[02:54:36 WARN]:        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264)
[02:54:36 WARN]:        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:316)
[02:54:36 WARN]:        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:404)
[02:54:36 WARN]:        at com.rylinaux.plugman.util.PluginUtil.load(PluginUtil.java:366)
[02:54:36 WARN]:        at com.rylinaux.plugman.util.PluginUtil.load(PluginUtil.java:318)
[02:54:36 WARN]:        at com.rylinaux.plugman.util.PluginUtil.reload(PluginUtil.java:380)
[02:54:36 WARN]:        at com.rylinaux.plugman.command.ReloadCommand.execute(ReloadCommand.java:122)
[02:54:36 WARN]:        at com.rylinaux.plugman.PlugManCommandHandler.onCommand(PlugManCommandHandler.java:95)
[02:54:36 WARN]:        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44)
[02:54:36 WARN]:        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:151)
[02:54:36 WARN]:        at org.bukkit.craftbukkit.v1_12_R1.CraftServer.dispatchCommand(CraftServer.java:672)
[02:54:36 WARN]:        at org.bukkit.craftbukkit.v1_12_R1.CraftServer.dispatchServerCommand(CraftServer.java:635)
[02:54:36 WARN]:        at net.minecraft.server.v1_12_R1.DedicatedServer.aP(DedicatedServer.java:462)
[02:54:36 WARN]:        at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:425)
[02:54:36 WARN]:        at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:767)
[02:54:36 WARN]:        at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:665)
[02:54:36 WARN]:        at java.lang.Thread.run(Thread.java:748)
```

**Comment by sgdc3** [comment]
any idea what could be wrong?

**Comment by sgdc3** [comment]
This is my transformer:

```
package it.feargames.askyblockfix;

import com.wasteofplastic.askyblock.ASkyBlock;
import com.wasteofplastic.askyblock.Island;
import com.wasteofplastic.askyblock.commands.IslandCmd;
import me.yamakaja.runtimetransformer.annotation.Inject;
import me.yamakaja.runtimetransformer.annotation.InjectionType;
import me.yamakaja.runtimetransformer.annotation.Transform;
import org.bukkit.Bukkit;
import org.bukkit.entity.Player;

@Transform(IslandCmd.class)
public class IslandCmdTransformer extends IslandCmd {

    public IslandCmdTransformer(ASkyBlock aSkyBlock) {
        super(aSkyBlock);
    }

    @Inject(InjectionType.INSERT)
    private void resetPlayer(Player player, Island oldIsland) {
        if(oldIsland != null) {
            Bukkit.getPluginManager().callEvent(new IslandPreResetEvent(player, oldIsland.getCenter()));
        }
    }
}
```

**Comment by Yamakaja** [comment]
Try removing the extends

**Comment by Yamakaja** [comment]
You can still access methods of the superclass like this: https://paste.md-5.net/busohodava.java (The invocation will just get rewritten)

**Comment by sgdc3** [comment]
is that correct?

```
package it.feargames.askyblockfix;

import com.wasteofplastic.askyblock.ASkyBlock;
import com.wasteofplastic.askyblock.Island;
import com.wasteofplastic.askyblock.commands.IslandCmd;
import me.yamakaja.runtimetransformer.annotation.Inject;
import me.yamakaja.runtimetransformer.annotation.InjectionType;
import me.yamakaja.runtimetransformer.annotation.Transform;
import org.bukkit.Bukkit;
import org.bukkit.entity.Player;

@Transform(IslandCmd.class)
public abstract class IslandCmdTransformer {

    @Inject(InjectionType.INSERT)
    private void resetPlayer(Player player, Island oldIsland) {
        if(oldIsland != null) {
            Bukkit.getPluginManager().callEvent(new IslandPreResetEvent(player, oldIsland.getCenter()));
        }
    }
}

```

**Comment by sgdc3** [comment]
Still throws the exception, @Yamakaja any idea?

**Comment by Yamakaja** [comment]
Alright, i think the issue might be with Bukkits classloader separation. I hope i'll be able to take a closer look tomorrow

**Comment by Yamakaja** [comment]
@sgdc3 https://github.com/Yamakaja/RuntimeTransformer/commit/97688c42655893e6f3b40dc2176cf8a724e24404 should finally fix it

**Comment by TuxCoding** [comment]
>Yeah, this is caused by the fact that the tools.jar classes are not available, contrary to the belief of #2 's issuer. Currently working on an adequate fix

@Yamakaja It's available, but it have to be loaded either using the manifest file in the main jar or using the dynamically loading. Packaging the tools jars might not be really useful, because as I said it's platform dependent and maybe should only included in subproject that you can add optionally. 

**Big sorry** that I didn't noticed that. I already loaded the tools jar in another project. So I didn't got this Exception.

>about missing agent.jar in the final jar -_- then i manually copied the agent.jar into the final jar and got this:

Building it locally I didn't got this issue. It appears to have issues with the command it runs at Jiitpack:

Jiitpack command
`gradle clean -Pgroup=com.github.games647 -Pversion=XXXXXX -xtest build publishToMavenLocal`

If you remove the -Pversion it works, but I have no idea about a workaround for Jiitpack.

**Comment by Yamakaja** [comment]
@games647 The dynamic loading route seems to be the best option for now.

Regarding jitpack, i'll see what i can do

**Comment by sgdc3** [comment]
Any ideas how to bypass the bukkit plugin classpath security?

**Comment by TuxCoding** [comment]
@Yamakaja Found it. It's the different agent jar name it generates if you use `-Pversion`. 

Changes for a fix: https://github.com/games647/RuntimeTransformer/blob/c818a9c79f63fa16660f8744a48617d646573341/agent/build.gradle#L22

Final jar: https://jitpack.io/com/github/games647/RuntimeTransformer/api/testing-c818a9c79f-1/api-testing-c818a9c79f-1.jar

@sgdc3 It should work with @Yamakaja changes. At least it doesn't throw exceptions on startup. Didn't test it further.

**Comment by Yamakaja** [comment]
@sgdc3 What do you mean?

If you mean that it couldn't find that class: That happened because the ASM used the system class loader to try and resolve the plugin classes, which were loaded by the plugin class loader and therefore not available to the system one.

**Comment by sgdc3** [comment]
@Yamakaja Ah ok, is it possible to make asm use a specified class loader?

**Comment by Yamakaja** [comment]
That's exactly what i did: https://github.com/Yamakaja/RuntimeTransformer/blob/master/agent/src/main/java/me/yamakaja/runtimetransformer/transform/ClassTransformer.java#L51-L75

**Comment by Yamakaja** [comment]
Or https://github.com/Yamakaja/RuntimeTransformer/blob/master/agent/src/main/java/me/yamakaja/runtimetransformer/transform/ClassTransformer.java#L55-L56 to be more precise.
"loader" is the class loader of the class which is being retransformed

**Comment by sgdc3** [comment]
@Yamakaja Uh i messed your commit ;)

**Comment by Yamakaja** [comment]
@sgdc3 Does it work now?

**Comment by sgdc3** [comment]
Same exception :/ Idk if maven is ignoring the new local library version

**Comment by Yamakaja** [comment]
Stacktrace please

**Comment by sgdc3** [comment]
Ok, it was an issue on my end, seems to work now ;)

**Comment by Yamakaja** [comment]
*sigh* finally :smile:

**Comment by sgdc3** [comment]
One last question, what happens if i reload the plugin? Does it duplicate the injected code?

**Comment by Yamakaja** [comment]
Yeah, you optimally wouldn't want to allow reloading

**Comment by sgdc3** [comment]
can i call the original method from an ovverride injected method?

**Comment by sgdc3** [comment]
but that would anyway duplicate the code :/

**Comment by Yamakaja** [comment]
Well no, you're overwriting the code of the method. You'd probably want to insert something.

What exactly do you want to achieve, maybe that helps me explain it

**Comment by sgdc3** [comment]
That's what i'm currently doing, but i'll need something to prevent code duplication on reload

**Comment by Yamakaja** [comment]
Write a system property and only invoke the runtime transformer if that system property isn't present yet?

**Comment by Yamakaja** [comment]
Well, the other way around. But you get what i mean
